In [1]:
import csv
import os
import pandas as pd

In [2]:
# Source CSV file path
source_folder = r'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files'
csv_filename = 'public_up_to_150k_1_230101.csv'
source_csv_path = os.path.join(source_folder, csv_filename)

# Read the CSV file using pandas
df = pd.read_csv(source_csv_path)
df.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,3509338307,01/22/2021,NaN,PPS,Exemption 6,NaN,NaN,NaN,NaN,02/18/2022,...,Non-Profit Organization,NaN,NaN,NaN,NaN,Unanswered,Unanswered,Y,150775.38,01/13/2022
1,5375617707,05/01/2020,101.0,PPP,NOT AVAILABLE,NaN,NaN,NaN,NaN,07/16/2021,...,NaN,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,NaN,150083.01,06/11/2021
2,9677497701,05/01/2020,464.0,PPP,NORTH CHARLESTON HOSPITALITY GROUP LLC,192 College Park Rd,Ladson,NaN,29456-3517,09/25/2021,...,Limited Liability Company(LLC),19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,141920.11,08/25/2021
3,9547167709,05/01/2020,464.0,PPP,Q AND J SERVICES LLC,301 Old Georgetown Road,Manning,NaN,29102-2734,04/20/2021,...,Limited Liability Company(LLC),19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,137747.78,03/29/2021
4,8885207205,04/28/2020,NaN,PPP,Exemption 6,NaN,NaN,NaN,NaN,05/20/2021,...,Non-Profit Organization,NaN,NaN,NaN,NaN,Unanswered,Unanswered,Y,131876.98,04/27/2021

In [3]:
#filtering the data by country, state, congressional district, and business size

# Filter conditions
condition_method = df['ProcessingMethod'] == 'PPP'
condition_NAICS = df['NAICSCode'] == 541330

# Combine the conditions using logical AND
combined_condition = condition_method & condition_NAICS

# Apply the combined condition to filter the DataFrame
df_filtered = df[combined_condition]
df_filtered.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
24,9788467706,05/01/2020,101.0,PPP,SHOCKWAVE AVIATION LLC,NaN,NaN,NaN,NaN,11/17/2021,...,NaN,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,42001.34,02/24/2021
186,7253527008,04/07/2020,1084.0,PPP,"CE2 ENGINEERS, INC.",8221 DIMOND HOOK DR,ANCHORAGE,AK,99507-3154,09/25/2021,...,Subchapter S Corporation,116975.0,Northrim Bank,ANCHORAGE,AK,Unanswered,Unanswered,NaN,150735.01,08/24/2021
193,4879527703,05/01/2020,1084.0,PPP,MCLANE CONSULTING INC,38240 KENAI SPUR HWY,SOLDOTNA,AK,99669,05/08/2021,...,Corporation,12096.0,"Wells Fargo Bank, National Association",SIOUX FALLS,SD,Unanswered,Unanswered,NaN,149560.22,04/08/2021
306,3412177108,04/11/2020,1084.0,PPP,HMS INC,4103 MINNESOTA DRIVE,ANCHORAGE,AK,99503-6448,03/12/2021,...,Corporation,3386.0,First National Bank Alaska,ANCHORAGE,AK,Unanswered,Unanswered,NaN,144063.25,02/25/2021
473,5206547208,04/27/2020,1084.0,PPP,BEZEK-DURST-SEISER INC,3330 C ST SUITE 200,ANCHORAGE,AK,99503,04/20/2021,...,Corporation,116975.0,Northrim Bank,ANCHORAGE,AK,Male Owned,Non-Veteran,NaN,137311.28,03/11/2021

In [4]:
df_filtered.shape

(3058, 53)

In [5]:
# Define the CSV filename
filtered_csv_filename = 'PPP_NAICS_Eng_1.csv'

# Define the full path for the filtered CSV file
filtered_csv_path = os.path.join(source_folder, filtered_csv_filename)

# Save the filtered DataFrame as a CSV file
df_filtered.to_csv(filtered_csv_path, index=False)

print(f"Filtered DataFrame saved as '{filtered_csv_path}'")

Filtered DataFrame saved as 'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files\PPP_NAICS_Eng_1.csv'