In [1]:
import csv
import os
import pandas as pd

In [2]:
# Source CSV file path
source_folder = r'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files'
csv_filename = 'public_up_to_150k_3_230101.csv'
source_csv_path = os.path.join(source_folder, csv_filename)

# Read the CSV file using pandas
df = pd.read_csv(source_csv_path)
df.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,5842618605,03/20/2021,156,PPP,REEVE MOORE,4 Catbriar Ln,Old Lyme,CT,06371-1481,10/20/2021,...,Sole Proprietorship,12096,"Wells Fargo Bank, National Association",SIOUX FALLS,SD,Unanswered,Unanswered,NaN,18565.59,09/15/2021
1,3284178109,07/14/2020,156,PPP,A LASZLO PAINTING LLC,3 LINDENCREST DR,DANBURY,CT,06811,01/20/2022,...,Self-Employed Individuals,15940,Webster Bank National Association,WATERBURY,CT,Unanswered,Unanswered,NaN,18734.66,12/16/2021
2,4167858902,04/28/2021,156,PPP,FULL CIRCLE HEALING GROUP LLC,1 Willowbrook Rd Ste 6,Cromwell,CT,06416-1745,NaN,...,Single Member LLC,434162,"Citizens Bank, National Association",PROVIDENCE,RI,Female Owned,Unanswered,NaN,NaN,NaN
3,5343878804,04/17/2021,156,PPP,SABIA ENTERPRISES LLC,325 Hathaway Dr,Stratford,CT,06615-7357,03/09/2022,...,Single Member LLC,16403,Newtown Savings Bank,NEWTOWN,CT,Unanswered,Unanswered,NaN,18615.62,01/28/2022
4,2987337202,04/16/2020,156,PPP,SUMMIT ENTERTAINMENT GROUP LLC,10 POTTER HILL DR,GUILFORD,CT,06437-2176,04/16/2021,...,Limited Liability Company(LLC),9551,"Bank of America, National Association",CHARLOTTE,NC,Female Owned,Non-Veteran,NaN,18630.91,02/25/2021

In [3]:
#filtering the data by country, state, congressional district, and business size

# Filter conditions
condition_method = df['ProcessingMethod'] == 'PPP'
condition_NAICS = df['NAICSCode'] == 541330

# Combine the conditions using logical AND
combined_condition = condition_method & condition_NAICS

# Apply the combined condition to filter the DataFrame
df_filtered = df[combined_condition]
df_filtered.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
766,7531497100,04/14/2020,156,PPP,REDDING STEEL,90 WHITE OAK DRIVE,Southington,CT,06489,01/22/2021,...,Partnership,29805,"TD Bank, National Association",WILMINGTON,DE,Unanswered,Unanswered,NaN,18160.27,12/21/2020
1200,7538547301,04/30/2020,156,PPP,"JEMAR MECHANICAL, LLC",798 OCEAN AVE,WEST HAVEN,CT,06516,10/08/2021,...,Limited Liability Company(LLC),46391,Manufacturers and Traders Trust Company,BUFFALO,NY,Unanswered,Unanswered,NaN,18076.56,09/01/2021
1387,8369407210,04/28/2020,156,PPP,HAYWARD-HOLBROOK ENGINEERS & SURVEYORS,12 ROOSEVELT AVE,MYSTIC,CT,06355-2809,10/09/2021,...,Sole Proprietorship,16318,Chelsea Groton Bank,NORWICH,CT,Unanswered,Unanswered,NaN,17959.12,08/02/2021
1626,9074968708,04/08/2021,156,PPP,SEAN MICHAEL BLONDIN,8 Melody Ln,East Granby,CT,06026-9732,11/19/2021,...,Self-Employed Individuals,56102,KeyBank National Association,CLEVELAND,OH,Unanswered,Unanswered,NaN,17706.89,10/20/2021
1969,7958587102,04/14/2020,156,PPP,EGC ENVIRONMENTAL SERVICES INC.,248 NORTH PARKER HILL RD,KILLINGWORTH,CT,06419-1165,12/14/2021,...,Subchapter S Corporation,46391,Manufacturers and Traders Trust Company,BUFFALO,NY,Unanswered,Unanswered,NaN,17762.26,10/28/2021

In [4]:
df_filtered.shape

(2136, 53)

In [5]:
# Define the CSV filename
filtered_csv_filename = 'PPP_NAICS_Eng_3.csv'

# Define the full path for the filtered CSV file
filtered_csv_path = os.path.join(source_folder, filtered_csv_filename)

# Save the filtered DataFrame as a CSV file
df_filtered.to_csv(filtered_csv_path, index=False)

print(f"Filtered DataFrame saved as '{filtered_csv_path}'")

Filtered DataFrame saved as 'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files\PPP_NAICS_Eng_3.csv'