In [1]:
import csv
import os
import pandas as pd

In [2]:
# Source CSV file path
source_folder = r'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files'
csv_filename = 'public_up_to_150k_6_230101.csv'
source_csv_path = os.path.join(source_folder, csv_filename)

# Read the CSV file using pandas
df = pd.read_csv(source_csv_path)
df.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,7508917707,05/01/2020,457,PPP,CRAVE CAFE & CATERING,2250 FRANKFORT AVE,LOUISVILLE,KY,40206,03/23/2021,...,Limited Liability Company(LLC),53803,"U.S. Bank, National Association",CINCINNATI,OH,Female Owned,Unanswered,NaN,16808.17,12/09/2020
1,4819588301,01/23/2021,457,PPS,RICHWOOD ON THE RIVER,1233 Highway 36,Milton,KY,40045-8229,08/17/2021,...,Limited Liability Company(LLC),57328,The Huntington National Bank,COLUMBUS,OH,Female Owned,Non-Veteran,NaN,22853.29,07/26/2021
2,5138028307,01/25/2021,457,PPS,JOELLES BAKERY AND CAFE LLC,225 Burley Ave,Hopkinsville,KY,42240-8725,11/06/2021,...,Limited Liability Company(LLC),120955,"Planters Bank, Inc.",HOPKINSVILLE,KY,Unanswered,Unanswered,NaN,22902.20,10/06/2021
3,6684998307,01/27/2021,457,PPS,WESTPORT VILLAGE JEWELRY LLC,14607 Harkaway Ave,Louisville,KY,40299-6855,11/11/2021,...,Limited Liability Company(LLC),44449,"PNC Bank, National Association",WILMINGTON,DE,Unanswered,Unanswered,NaN,22896.16,10/08/2021
4,3249787407,05/07/2020,457,PPP,DAVID L. LAND,237 LEXINGTON ST,LANCASTER,KY,40444-1184,03/18/2021,...,Self-Employed Individuals,26908,"Whitaker Bank, Inc",LEXINGTON,KY,Unanswered,Unanswered,NaN,22925.09,03/05/2021

In [3]:
#filtering the data by country, state, congressional district, and business size

# Filter conditions
condition_method = df['ProcessingMethod'] == 'PPP'
condition_NAICS = df['NAICSCode'] == 541330

# Combine the conditions using logical AND
combined_condition = condition_method & condition_NAICS

# Apply the combined condition to filter the DataFrame
df_filtered = df[combined_condition]
df_filtered.head()

,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
915,6687407010,04/07/2020,457,PPP,"MARCUM ENERGY MANAGEMENT SOLUTIONS, INC",500 S 17TH ST,PADUCAH,KY,42003-2819,07/21/2021,...,Corporation,27680,The Paducah Bank and Trust Company,PADUCAH,KY,Unanswered,Unanswered,NaN,21961.59,07/02/2021
1108,7728577104,04/14/2020,457,PPP,CYRUS ENGINEERING,2701 LINDSAY AVE,LOUISVILLE,KY,40206-2222,04/16/2021,...,Limited Liability Company(LLC),27542,Republic Bank & Trust Company,LOUISVILLE,KY,Unanswered,Unanswered,NaN,21700.67,03/23/2021
1475,2220497100,04/10/2020,457,PPP,"VINSAND ENGINEERING AND LAND SURVEYING, INCORP...",306 W JEFFERSON ST,LA GRANGE,KY,40031-1112,05/15/2021,...,Corporation,27542,Republic Bank & Trust Company,LOUISVILLE,KY,Male Owned,Unanswered,NaN,20557.41,04/06/2021
1706,3948767204,04/27/2020,457,PPP,EXCELLENCE IN LEAN LLC,80 LAKE CLIFF DR,SOMERSET,KY,42503-9728,11/06/2020,...,Limited Liability Company(LLC),26835,Citizens Bank,MOUNT VERNON,KY,Unanswered,Unanswered,NaN,20964.22,10/09/2020
4933,6695127401,05/15/2020,457,PPP,MLH CIVIL ENGINEERS PLLC,3320 CLAYS MILL RD Suite 208,LEXINGTON,KY,40503-3484,01/21/2021,...,Limited Liability Partnership,26832,Meade County Bank,BRANDENBURG,KY,Unanswered,Unanswered,NaN,20948.48,12/09/2020

In [4]:
df_filtered.shape

(2344, 53)

In [5]:
# Define the CSV filename
filtered_csv_filename = 'PPP_NAICS_Eng_6.csv'

# Define the full path for the filtered CSV file
filtered_csv_path = os.path.join(source_folder, filtered_csv_filename)

# Save the filtered DataFrame as a CSV file
df_filtered.to_csv(filtered_csv_path, index=False)

print(f"Filtered DataFrame saved as '{filtered_csv_path}'")

Filtered DataFrame saved as 'F:\FAU PhD\DISSERTATION\DATABASES\ALL PPP Loan Data\PPP Orig csv Files\PPP_NAICS_Eng_6.csv'